<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-JLSUG9BU" failures="1" tests="5" name="Test" time="99.216" errors="0" timestamp="2025-08-30T18:30:59 IST">
  <testcase classname="com.testcase.DemoKartTestSuite" name="tc001_addToCartWithoutLogin" time="0.282"/>
  <testcase classname="com.testcase.DemoKartTestSuite" name="tc002_loginWithValidCredentials" time="0.45"/>
  <testcase classname="com.testcase.DemoKartTestSuite" name="tc003_welcomeBackToastOnProductPage" time="1.165"/>
  <testcase classname="com.testcase.DemoKartTestSuite" name="tc004_addToCartAndValidateUrl" time="0.466">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Phone 15 Pro Max has been added to your cart] but found [iPhone 15 Pro Max has been added to your cart]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Phone 15 Pro Max has been added to your cart] but found [iPhone 15 Pro Max has been added to your cart]
at com.testcase.DemoKartTestSuite.tc004_addToCartAndValidateUrl(DemoKartTestSuite.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- tc004_addToCartAndValidateUrl -->
  <testcase classname="com.testcase.DemoKartTestSuite" name="tc005_checkoutAndOrderConfirmation" time="3.932"/>
</testsuite> <!-- Test -->
